title: Anandsingh Chauhan
logo: /assets/img/headshot_circle_.jpg
description: Researcher working on simulation and control of future power systems using artificial intelligence. Most interested in integration of demand flexibility.
theme: jekyll-theme-minimal
