title: Anand Singh Chauhan
description: Researcher at TCS Research
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://anandsingh.github.io/Anandsingh-Chauhan" # the base hostname & protocol for your site
twitter_username: anandchauhan
github_username: anandsingh3996
linkedin_username: anandsingh3996

# Build settings
theme: "minimal-mistakes-jekyll"

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Navigation
header_pages:
  - index.md
  - cv.md
  - projects.md
  - publications.md
  - awards.md
  - contact.md

